

export const PANTALLAS = [
    { key: 'home', label: 'Home' },
    { key: 'muestras', label: 'Muestras' },
    { key: 'permiso', label: 'Permisos' },
    { key: 'programa', label: 'Programas' },
    { key: 'inspeccion_silo', label: 'Inspección Silos' },
    { key: 'inspeccion_est', label: 'Inspección Rutinaria' },
    { key: 'planificacion', label: 'Planificación' },
    { key: 'solicitud', label: 'Solicitud' },
    { key: 'propiedad', label: 'Propiedad' },
    { key: 'productor', label: 'Productor' },
    { key: 'laboratorio', label: 'Laboratorios' },
    { key: 'plaga', label: 'Plagas' },
    { key: 'cultivo', label: 'Cultivos' },
    { key: 'tipo_inspeccion', label: 'Tipos de Inspección' },
    { key: 'tipo_solicitud', label: 'Tipos de Solicitud' },
    { key: 'tipo_permiso', label: 'Tipos de Permisos' },
    { key: 'tipo_evento', label: 'Tipos de Eventos' },
    { key: 'tipo_propiedad', label: 'Tipos de Propiedad' },
    { key: 'tipo_productor', label: 'Tipos de Productor' },
    { key: 'tipo_programa', label: 'Tipos de Programas' },
    { key: 'tipo_laboratorio', label: 'Tipos de Laboratorios' },
    { key: 'tipo_plaga', label: 'Tipos de plagas' },
    { key: 'tipo_cultivo', label: 'Tipos de cultivos' },
    { key: 'estado', label: 'estados' },
    { key: 'municipio', label: 'Municipios' },
    { key: 'parroquia', label: 'Parroquias' },
    { key: 'sector', label: 'Sector' },
    { key: 'miusuario', label: 'Mi Usuario'},
    { key: 'usuarios', label: 'Usuarios' },
    { key: 'empleados', label: 'Empleados' },
    { key: 'cargos', label: 'Cargos' },
    { key: 'tipo_usuario', label: 'Roles & Permisos' },
    { key: 'bitacora', label: 'Bitacora' },
    ];

export const ACCIONES = [
    { key: 'ver', label: 'Ver' },
    { key: 'crear', label: 'Crear' },
    { key: 'editar', label: 'Editar' },
    { key: 'deshabilitar', label: 'Deshabilitar' },
    { key: 'eliminar', label: 'Eliminar' },
    ];
