

export const PANTALLAS = [
    { key: 'home', label: 'Home', acciones: ['ver', 'exportar'] },
    { key: 'programa', label: 'Programas', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar']},
    { key: 'inspecciones', label: 'Inspecciones' , acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar']},
    { key: 'planificacion', label: 'Planificaciones' , acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar']},
    { key: 'solicitud', label: 'Solicitudes' , acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar']},
    { key: 'propiedad', label: 'Propiedades' , acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar']},
    { key: 'productor', label: 'Productores' , acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar']},
    { key: 'laboratorio', label: 'Laboratorios' , acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar']},
    { key: 'plaga', label: 'Plagas' , acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar']},
    { key: 'cultivo', label: 'Cultivos' , acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar']},
    { key: 'tipo_inspeccion', label: 'Tipos de Inspección' , acciones: ['ver', 'crear', 'editar', 'eliminar']},
    { key: 'tipo_solicitud', label: 'Tipos de Solicitud', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'tipo_permiso', label: 'Tipos de Permisos', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'tipo_evento', label: 'Tipos de Eventos' , acciones: ['ver', 'crear', 'editar', 'eliminar']},
    { key: 'tipo_propiedad', label: 'Tipos de Propiedad', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'tipo_programa', label: 'Tipos de Programas', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'tipo_laboratorio', label: 'Tipos de Laboratorios', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'tipo_plaga', label: 'Tipos de plagas', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'tipo_cultivo', label: 'Tipos de cultivos', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'estado', label: 'estados', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'municipio', label: 'Municipios' , acciones: ['ver', 'crear', 'editar', 'eliminar']},
    { key: 'parroquia', label: 'Parroquias', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'sector', label: 'Sector', acciones: ['ver', 'crear', 'editar', 'eliminar']},
    { key: 'miusuario', label: 'Mi Usuario', acciones: ['ver', 'crear', 'editar', 'eliminar', 'exportar']},
    { key: 'usuarios', label: 'Usuarios', acciones: ['ver', 'crear', 'editar', 'deshabilitar','eliminar']},
    { key: 'empleados', label: 'Empleados', acciones: ['ver', 'crear', 'editar', 'deshabilitar', 'exportar','eliminar'] },
    { key: 'cargos', label: 'Cargos', acciones: ['ver', 'crear', 'editar', 'eliminar'] },
    { key: 'tipo_usuario', label: 'Roles', acciones: ['ver', 'crear', 'editar', 'eliminar']},
    { key: 'bitacora', label: 'Bitacora', acciones: ['ver']},
    ];

export const ACCIONES = [
    { key: 'ver', label: 'Ver' },
    { key: 'crear', label: 'Crear' },
    { key: 'editar', label: 'Editar' },
    { key: 'deshabilitar', label: 'Deshabilitar' },
    { key: 'eliminar', label: 'Eliminar' },
    { key: 'exportar', label: 'Exportar' },
];
